const messages = [
    "The Milky Way galaxy is estimated to be about 100,000 light-years in diameter.",
    "A day on Venus is longer than its year.",
    "The Sun is over 330,000 times more massive than the Earth.",
    "Black holes are regions in space where gravity is so strong that nothing, not even light, can escape.",
    "The Andromeda Galaxy is on a collision course with our Milky Way and will collide with it in about 4.5 billion years.",
    "The Hubble Space Telescope has provided stunning images of distant galaxies and nebulae.",
    "The largest volcano in the solar system is Olympus Mons on Mars.",
    "A year on Neptune is about 165 Earth years long.",
    "The Great Red Spot on Jupiter is a giant storm that has been raging for at least 350 years.",
    "The moon Io has more than 400 active volcanoes, making it one of the most geologically active bodies in the solar system.",
    "The Oort Cloud is a region in space where comets originate.",
    "The speed of light is approximately 186,282 miles per second (299,792,458 meters per second).",
    "Halley's Comet, one of the most famous comets, returns to the inner solar system about once every 76 years.",
    "The Sun's core is so hot and dense that nuclear fusion occurs, converting hydrogen into helium.",
    "The largest asteroid in the asteroid belt is Ceres, which is also classified as a dwarf planet.",
    "The Universe is approximately 13.8 billion years old.",
    "The term 'light-year' is a measure of distance, not time, and it represents the distance light travels in one year.",
    "The Crab Nebula is the remnant of a supernova explosion observed by Chinese astronomers in 1054.",
    "There are more stars in the observable universe than there are grains of sand on all the beaches on Earth.",
    "The coldest known place in the Universe is the Boomerang Nebula, with temperatures dropping to just 1 degree above absolute zero.",
    "The first exoplanet, a planet outside our solar system, was discovered in 1992.",
    "The asteroid belt, located between Mars and Jupiter, is made up of millions of rocky objects.",
    "The Kuiper Belt is a region beyond Neptune that contains icy bodies and dwarf planets.",
    "The largest planet in our solar system is Jupiter, which is over 11 times wider than Earth.",
    "The concept of dark matter is still a mystery to scientists, as it cannot be observed directly but is believed to make up a significant portion of the Universe's mass.",
    "Astronomers use the term 'naked eye planets' to refer to the five planets visible to the naked eye: Mercury, Venus, Mars, Jupiter, and Saturn.",
    "The first successful mission to land on Mars was the Viking 1 mission in 1976.",
    "The first artificial satellite, Sputnik 1, was launched by the Soviet Union in 1957.",
    "The largest volcano in the solar system is Olympus Mons on Mars, which is about 13.6 miles (22 kilometers) high.",
    "The concept of a 'wormhole' is a hypothetical passage through space-time that could create shortcuts for long journeys across the universe.",
    "A solar eclipse occurs when the Moon passes between the Sun and Earth, blocking out the Sun's light.",
    "The concept of the 'Goldilocks zone' refers to the region around a star where conditions are just right for liquid water to exist, potentially supporting life.",
    "The Sun's energy is produced through nuclear fusion, where hydrogen atoms combine to form helium.",
    "The largest volcano in the solar system is Olympus Mons on Mars, which is about 72,000 feet (22 kilometers) high.",
    "The redshift of galaxies is used to determine their distance from Earth, which has led to the discovery of the expanding universe.",
    "The Doppler effect causes the light from objects moving away from Earth to shift toward the red end of the spectrum, leading to redshift.",
    "The Great Barrier Reef is visible from space and is the world's largest coral reef system.",
    "The largest impact crater on Earth is the Vredefort Crater in South Africa, formed over 2 billion years ago.",
    "The concept of 'dark energy' is believed to be responsible for the accelerated expansion of the universe.",
    "The North Star, Polaris, remains nearly fixed in the northern sky and is used for navigation.",
    "Saturn's rings are made up of countless tiny particles of ice and rock.",
    "The Sun's core is estimated to be around 15 million degrees Celsius (27 million degrees Fahrenheit).",
    "A light-second is the distance that light travels in one second, which is about 186,282 miles (299,792 kilometers).",
    "The Apollo 11 mission in 1969 marked the first human landing on the Moon.",
    "The concept of 'dark matter' is believed to make up about 27% of the Universe's mass, although it cannot be observed directly.",
    "The largest volcano in the solar system is Olympus Mons on Mars, which is about 72,000 feet (22 kilometers) high.",
    "The Sun is a G-type main-sequence star, commonly referred to as a yellow dwarf.",
    "The concept of 'space-time' unifies space and time into a single, interconnected framework.",
    "The highest point on Mars is the Olympus Mons volcano, which is about 72,000 feet (22 kilometers) high.",
    "The term 'light pollution' refers to the brightening of the night sky due to artificial light, which can interfere with astronomical observations.",
    "The highest point on Earth is the summit of Mount Everest, standing at 29,032 feet (8,849 meters) above sea level.",
    "The concept of 'event horizons' surrounds black holes, where the escape velocity is greater than the speed of light.",
    "The largest moon in the solar system is Ganymede, which is even larger than the planet Mercury.",
    "The cosmic microwave background radiation is a remnant of the Big Bang and can be observed throughout the universe.",
    "The Hubble Space Telescope orbits Earth at an altitude of about 340 miles (550 kilometers).",
    "The asteroid belt is located between the orbits of Mars and Jupiter and is made up of rocky and metallic objects.",
    "The first human in space was Yuri Gagarin, a Soviet cosmonaut, who orbited Earth in 1961.",
    "The Hubble Space Telescope has provided detailed images of distant galaxies, nebulae, and star clusters.",
    "The Moon's gravitational influence causes tides on Earth.",
    "The concept of 'neutron stars' results from the collapsed cores of massive stars and is incredibly dense.",
    "The atmosphere of Venus is primarily composed of carbon dioxide, creating a runaway greenhouse effect and extreme heat.",
    "The largest canyon in the solar system is Valles Marineris on Mars, which is over 4,000 kilometers long.",
    "The concept of 'wormholes' is purely theoretical and has not been observed in reality.",
    "The Moon's surface is covered in a layer of fine dust called regolith.",
    "The first American woman in space was Sally Ride, who flew on the Space Shuttle Challenger in 1983.",
    "The Oort Cloud is a theoretical region beyond the Kuiper Belt that may contain comets.",
    "The concept of 'white dwarfs' represents the remnants of low- to medium-mass stars.",
    "The largest volcano in the solar system is Olympus Mons on Mars, which is about 72,000 feet (22 kilometers) high.",
    "The Sun's core temperature is estimated to be around 15 million degrees Celsius (27 million degrees Fahrenheit).",
    "A light-second is the distance that light travels in one second, which is about 186,282 miles (299,792 kilometers).",
    "The Apollo 11 mission in 1969 marked the first human landing on the Moon.",
    "The concept of 'dark matter' is believed to make up about 27% of the Universe's mass, although it cannot be observed directly.",
    "The largest volcano in the solar system is Olympus Mons on Mars, which is about 72,000 feet (22 kilometers) high.",
    "The Sun is a G-type main-sequence star, commonly referred to as a yellow dwarf.",
    "The concept of 'space-time' unifies space and time into a single, interconnected framework.",
    "The highest point on Mars is the Olympus Mons volcano, which is about 72,000 feet (22 kilometers) high.",
    "The term 'light pollution' refers to the brightening of the night sky due to artificial light, which can interfere with astronomical observations.",
    "The highest point on Earth is the summit of Mount Everest, standing at 29,032 feet (8,849 meters) above sea level.",
    "The concept of 'event horizons' surrounds black holes, where the escape velocity is greater than the speed of light.",
    "The largest moon in the solar system is Ganymede, which is even larger than the planet Mercury.",
    "The cosmic microwave background radiation is a remnant of the Big Bang and can be observed throughout the universe.",
    "The Hubble Space Telescope orbits Earth at an altitude of about 340 miles (550 kilometers).",
    "The asteroid belt is located between the orbits of Mars and Jupiter and is made up of rocky and metallic objects.",
    "The first human in space was Yuri Gagarin, a Soviet cosmonaut, who orbited Earth in 1961.",
    "The Hubble Space Telescope has provided detailed images of distant galaxies, nebulae, and star clusters.",
];
const messageDisplay = document.getElementById('display');
const generateBtn = document.getElementById('generate');

generateBtn.addEventListener('click', () => {
    messageDisplay.innerHTML = messages[Math.floor(Math.random() * 85)];
})